//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SISWin1.HastaXMLWebServisi {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="HastaServisiSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Kisi))]
    public partial class HastaServisi : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback KaydetOperationCompleted;
        
        private System.Threading.SendOrPostCallback HastalariListeleOperationCompleted;
        
        private System.Threading.SendOrPostCallback HastaGetirOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public HastaServisi() {
            this.Url = global::SISWin1.Properties.Settings.Default.SISWin1_HastaXMLWebServisi_HastaServisi;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event KaydetCompletedEventHandler KaydetCompleted;
        
        /// <remarks/>
        public event HastalariListeleCompletedEventHandler HastalariListeleCompleted;
        
        /// <remarks/>
        public event HastaGetirCompletedEventHandler HastaGetirCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Kaydet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Kaydet(Hasta hasta) {
            object[] results = this.Invoke("Kaydet", new object[] {
                        hasta});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void KaydetAsync(Hasta hasta) {
            this.KaydetAsync(hasta, null);
        }
        
        /// <remarks/>
        public void KaydetAsync(Hasta hasta, object userState) {
            if ((this.KaydetOperationCompleted == null)) {
                this.KaydetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKaydetOperationCompleted);
            }
            this.InvokeAsync("Kaydet", new object[] {
                        hasta}, this.KaydetOperationCompleted, userState);
        }
        
        private void OnKaydetOperationCompleted(object arg) {
            if ((this.KaydetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KaydetCompleted(this, new KaydetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HastalariListele", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Hasta[] HastalariListele(string ad, string soyad) {
            object[] results = this.Invoke("HastalariListele", new object[] {
                        ad,
                        soyad});
            return ((Hasta[])(results[0]));
        }
        
        /// <remarks/>
        public void HastalariListeleAsync(string ad, string soyad) {
            this.HastalariListeleAsync(ad, soyad, null);
        }
        
        /// <remarks/>
        public void HastalariListeleAsync(string ad, string soyad, object userState) {
            if ((this.HastalariListeleOperationCompleted == null)) {
                this.HastalariListeleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHastalariListeleOperationCompleted);
            }
            this.InvokeAsync("HastalariListele", new object[] {
                        ad,
                        soyad}, this.HastalariListeleOperationCompleted, userState);
        }
        
        private void OnHastalariListeleOperationCompleted(object arg) {
            if ((this.HastalariListeleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HastalariListeleCompleted(this, new HastalariListeleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HastaGetir", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Hasta HastaGetir(int hastaNo) {
            object[] results = this.Invoke("HastaGetir", new object[] {
                        hastaNo});
            return ((Hasta)(results[0]));
        }
        
        /// <remarks/>
        public void HastaGetirAsync(int hastaNo) {
            this.HastaGetirAsync(hastaNo, null);
        }
        
        /// <remarks/>
        public void HastaGetirAsync(int hastaNo, object userState) {
            if ((this.HastaGetirOperationCompleted == null)) {
                this.HastaGetirOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHastaGetirOperationCompleted);
            }
            this.InvokeAsync("HastaGetir", new object[] {
                        hastaNo}, this.HastaGetirOperationCompleted, userState);
        }
        
        private void OnHastaGetirOperationCompleted(object arg) {
            if ((this.HastaGetirCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HastaGetirCompleted(this, new HastaGetirCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Hasta : Kisi {
        
        private System.DateTime dogumTarihiField;
        
        private string cinsiyetiField;
        
        private string adresField;
        
        /// <remarks/>
        public System.DateTime DogumTarihi {
            get {
                return this.dogumTarihiField;
            }
            set {
                this.dogumTarihiField = value;
            }
        }
        
        /// <remarks/>
        public string Cinsiyeti {
            get {
                return this.cinsiyetiField;
            }
            set {
                this.cinsiyetiField = value;
            }
        }
        
        /// <remarks/>
        public string Adres {
            get {
                return this.adresField;
            }
            set {
                this.adresField = value;
            }
        }

       
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Hasta))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Kisi {
        
        private int noField;
        
        private string tCKimlikNoField;
        
        private string adField;
        
        private string soyadField;
        
        private string epostaField;
        
        private string cepTelField;
        
        private string evTelField;
        
        /// <remarks/>
        public int No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        public string TCKimlikNo {
            get {
                return this.tCKimlikNoField;
            }
            set {
                this.tCKimlikNoField = value;
            }
        }
        
        /// <remarks/>
        public string Ad {
            get {
                return this.adField;
            }
            set {
                this.adField = value;
            }
        }
        
        /// <remarks/>
        public string Soyad {
            get {
                return this.soyadField;
            }
            set {
                this.soyadField = value;
            }
        }
        
        /// <remarks/>
        public string Eposta {
            get {
                return this.epostaField;
            }
            set {
                this.epostaField = value;
            }
        }
        
        /// <remarks/>
        public string CepTel {
            get {
                return this.cepTelField;
            }
            set {
                this.cepTelField = value;
            }
        }
        
        /// <remarks/>
        public string EvTel {
            get {
                return this.evTelField;
            }
            set {
                this.evTelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void KaydetCompletedEventHandler(object sender, KaydetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KaydetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KaydetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void HastalariListeleCompletedEventHandler(object sender, HastalariListeleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HastalariListeleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HastalariListeleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Hasta[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Hasta[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void HastaGetirCompletedEventHandler(object sender, HastaGetirCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HastaGetirCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HastaGetirCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Hasta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Hasta)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591