//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SISWin1.SeansXMLWebServisi {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SeansServisiSoap", Namespace="http://tempuri.org/")]
    public partial class SeansServisi : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback KaydetOperationCompleted;
        
        private System.Threading.SendOrPostCallback UzmanSeanslariniListeleOperationCompleted;
        
        private System.Threading.SendOrPostCallback IptalEtOperationCompleted;
        
        private System.Threading.SendOrPostCallback SonSeansBilgisiGetirOperationCompleted;
        
        private System.Threading.SendOrPostCallback SonRandevuBilgisiGetirOperationCompleted;
        
        private System.Threading.SendOrPostCallback RandevuKaydetOperationCompleted;
        
        private System.Threading.SendOrPostCallback RandevuIptalEtOperationCompleted;
        
        private System.Threading.SendOrPostCallback HastaSeanslariniListeleOperationCompleted;
        
        private System.Threading.SendOrPostCallback NotGuncelleOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SeansServisi() {
            this.Url = global::SISWin1.Properties.Settings.Default.SISWin1_SeansXMLWebServisi_SeansServisi;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event KaydetCompletedEventHandler KaydetCompleted;
        
        /// <remarks/>
        public event UzmanSeanslariniListeleCompletedEventHandler UzmanSeanslariniListeleCompleted;
        
        /// <remarks/>
        public event IptalEtCompletedEventHandler IptalEtCompleted;
        
        /// <remarks/>
        public event SonSeansBilgisiGetirCompletedEventHandler SonSeansBilgisiGetirCompleted;
        
        /// <remarks/>
        public event SonRandevuBilgisiGetirCompletedEventHandler SonRandevuBilgisiGetirCompleted;
        
        /// <remarks/>
        public event RandevuKaydetCompletedEventHandler RandevuKaydetCompleted;
        
        /// <remarks/>
        public event RandevuIptalEtCompletedEventHandler RandevuIptalEtCompleted;
        
        /// <remarks/>
        public event HastaSeanslariniListeleCompletedEventHandler HastaSeanslariniListeleCompleted;
        
        /// <remarks/>
        public event NotGuncelleCompletedEventHandler NotGuncelleCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Kaydet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Kaydet(Seans seans) {
            object[] results = this.Invoke("Kaydet", new object[] {
                        seans});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void KaydetAsync(Seans seans) {
            this.KaydetAsync(seans, null);
        }
        
        /// <remarks/>
        public void KaydetAsync(Seans seans, object userState) {
            if ((this.KaydetOperationCompleted == null)) {
                this.KaydetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKaydetOperationCompleted);
            }
            this.InvokeAsync("Kaydet", new object[] {
                        seans}, this.KaydetOperationCompleted, userState);
        }
        
        private void OnKaydetOperationCompleted(object arg) {
            if ((this.KaydetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KaydetCompleted(this, new KaydetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UzmanSeanslariniListele", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Seans[] UzmanSeanslariniListele(int uzmanNo) {
            object[] results = this.Invoke("UzmanSeanslariniListele", new object[] {
                        uzmanNo});
            return ((Seans[])(results[0]));
        }
        
        /// <remarks/>
        public void UzmanSeanslariniListeleAsync(int uzmanNo) {
            this.UzmanSeanslariniListeleAsync(uzmanNo, null);
        }
        
        /// <remarks/>
        public void UzmanSeanslariniListeleAsync(int uzmanNo, object userState) {
            if ((this.UzmanSeanslariniListeleOperationCompleted == null)) {
                this.UzmanSeanslariniListeleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUzmanSeanslariniListeleOperationCompleted);
            }
            this.InvokeAsync("UzmanSeanslariniListele", new object[] {
                        uzmanNo}, this.UzmanSeanslariniListeleOperationCompleted, userState);
        }
        
        private void OnUzmanSeanslariniListeleOperationCompleted(object arg) {
            if ((this.UzmanSeanslariniListeleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UzmanSeanslariniListeleCompleted(this, new UzmanSeanslariniListeleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IptalEt", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IptalEt(Seans seans) {
            object[] results = this.Invoke("IptalEt", new object[] {
                        seans});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IptalEtAsync(Seans seans) {
            this.IptalEtAsync(seans, null);
        }
        
        /// <remarks/>
        public void IptalEtAsync(Seans seans, object userState) {
            if ((this.IptalEtOperationCompleted == null)) {
                this.IptalEtOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIptalEtOperationCompleted);
            }
            this.InvokeAsync("IptalEt", new object[] {
                        seans}, this.IptalEtOperationCompleted, userState);
        }
        
        private void OnIptalEtOperationCompleted(object arg) {
            if ((this.IptalEtCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IptalEtCompleted(this, new IptalEtCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SonSeansBilgisiGetir", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Seans SonSeansBilgisiGetir(int hastaNo) {
            object[] results = this.Invoke("SonSeansBilgisiGetir", new object[] {
                        hastaNo});
            return ((Seans)(results[0]));
        }
        
        /// <remarks/>
        public void SonSeansBilgisiGetirAsync(int hastaNo) {
            this.SonSeansBilgisiGetirAsync(hastaNo, null);
        }
        
        /// <remarks/>
        public void SonSeansBilgisiGetirAsync(int hastaNo, object userState) {
            if ((this.SonSeansBilgisiGetirOperationCompleted == null)) {
                this.SonSeansBilgisiGetirOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSonSeansBilgisiGetirOperationCompleted);
            }
            this.InvokeAsync("SonSeansBilgisiGetir", new object[] {
                        hastaNo}, this.SonSeansBilgisiGetirOperationCompleted, userState);
        }
        
        private void OnSonSeansBilgisiGetirOperationCompleted(object arg) {
            if ((this.SonSeansBilgisiGetirCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SonSeansBilgisiGetirCompleted(this, new SonSeansBilgisiGetirCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SonRandevuBilgisiGetir", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Seans SonRandevuBilgisiGetir(int hastaNo) {
            object[] results = this.Invoke("SonRandevuBilgisiGetir", new object[] {
                        hastaNo});
            return ((Seans)(results[0]));
        }
        
        /// <remarks/>
        public void SonRandevuBilgisiGetirAsync(int hastaNo) {
            this.SonRandevuBilgisiGetirAsync(hastaNo, null);
        }
        
        /// <remarks/>
        public void SonRandevuBilgisiGetirAsync(int hastaNo, object userState) {
            if ((this.SonRandevuBilgisiGetirOperationCompleted == null)) {
                this.SonRandevuBilgisiGetirOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSonRandevuBilgisiGetirOperationCompleted);
            }
            this.InvokeAsync("SonRandevuBilgisiGetir", new object[] {
                        hastaNo}, this.SonRandevuBilgisiGetirOperationCompleted, userState);
        }
        
        private void OnSonRandevuBilgisiGetirOperationCompleted(object arg) {
            if ((this.SonRandevuBilgisiGetirCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SonRandevuBilgisiGetirCompleted(this, new SonRandevuBilgisiGetirCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RandevuKaydet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RandevuKaydet(int seansNo, int hastaNo) {
            object[] results = this.Invoke("RandevuKaydet", new object[] {
                        seansNo,
                        hastaNo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RandevuKaydetAsync(int seansNo, int hastaNo) {
            this.RandevuKaydetAsync(seansNo, hastaNo, null);
        }
        
        /// <remarks/>
        public void RandevuKaydetAsync(int seansNo, int hastaNo, object userState) {
            if ((this.RandevuKaydetOperationCompleted == null)) {
                this.RandevuKaydetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRandevuKaydetOperationCompleted);
            }
            this.InvokeAsync("RandevuKaydet", new object[] {
                        seansNo,
                        hastaNo}, this.RandevuKaydetOperationCompleted, userState);
        }
        
        private void OnRandevuKaydetOperationCompleted(object arg) {
            if ((this.RandevuKaydetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RandevuKaydetCompleted(this, new RandevuKaydetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RandevuIptalEt", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RandevuIptalEt(int seansNo) {
            object[] results = this.Invoke("RandevuIptalEt", new object[] {
                        seansNo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RandevuIptalEtAsync(int seansNo) {
            this.RandevuIptalEtAsync(seansNo, null);
        }
        
        /// <remarks/>
        public void RandevuIptalEtAsync(int seansNo, object userState) {
            if ((this.RandevuIptalEtOperationCompleted == null)) {
                this.RandevuIptalEtOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRandevuIptalEtOperationCompleted);
            }
            this.InvokeAsync("RandevuIptalEt", new object[] {
                        seansNo}, this.RandevuIptalEtOperationCompleted, userState);
        }
        
        private void OnRandevuIptalEtOperationCompleted(object arg) {
            if ((this.RandevuIptalEtCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RandevuIptalEtCompleted(this, new RandevuIptalEtCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HastaSeanslariniListele", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Seans[] HastaSeanslariniListele(int hastaNo) {
            object[] results = this.Invoke("HastaSeanslariniListele", new object[] {
                        hastaNo});
            return ((Seans[])(results[0]));
        }
        
        /// <remarks/>
        public void HastaSeanslariniListeleAsync(int hastaNo) {
            this.HastaSeanslariniListeleAsync(hastaNo, null);
        }
        
        /// <remarks/>
        public void HastaSeanslariniListeleAsync(int hastaNo, object userState) {
            if ((this.HastaSeanslariniListeleOperationCompleted == null)) {
                this.HastaSeanslariniListeleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHastaSeanslariniListeleOperationCompleted);
            }
            this.InvokeAsync("HastaSeanslariniListele", new object[] {
                        hastaNo}, this.HastaSeanslariniListeleOperationCompleted, userState);
        }
        
        private void OnHastaSeanslariniListeleOperationCompleted(object arg) {
            if ((this.HastaSeanslariniListeleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HastaSeanslariniListeleCompleted(this, new HastaSeanslariniListeleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NotGuncelle", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool NotGuncelle(int seansNo, string seansNotu) {
            object[] results = this.Invoke("NotGuncelle", new object[] {
                        seansNo,
                        seansNotu});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void NotGuncelleAsync(int seansNo, string seansNotu) {
            this.NotGuncelleAsync(seansNo, seansNotu, null);
        }
        
        /// <remarks/>
        public void NotGuncelleAsync(int seansNo, string seansNotu, object userState) {
            if ((this.NotGuncelleOperationCompleted == null)) {
                this.NotGuncelleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNotGuncelleOperationCompleted);
            }
            this.InvokeAsync("NotGuncelle", new object[] {
                        seansNo,
                        seansNotu}, this.NotGuncelleOperationCompleted, userState);
        }
        
        private void OnNotGuncelleOperationCompleted(object arg) {
            if ((this.NotGuncelleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NotGuncelleCompleted(this, new NotGuncelleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Seans {
       
        private int noField;
        
        private int uzmanNoField;
        
        private int hastaNoField;
        
        private System.DateTime tarihField;
        
        private string baslangicSaatiField;
        
        private string bitisSaatiField;
        
        private string seansNotuField;
        
        private int iptalEdenNoField;
        
        private string iptalNotuField;
        
        private string hastaBilgisiField;
        
        private string uzmanBilgisiField;
        
        private bool seansYapildiField;
        
        private bool hastaIptalEttiField;

  
        /// <remarks/>
        public int No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        public int UzmanNo {
            get {
                return this.uzmanNoField;
            }
            set {
                this.uzmanNoField = value;
            }
        }
        
        /// <remarks/>
        public int HastaNo {
            get {
                return this.hastaNoField;
            }
            set {
                this.hastaNoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Tarih {
            get {
                return this.tarihField;
            }
            set {
                this.tarihField = value;
            }
        }
        
        /// <remarks/>
        public string BaslangicSaati {
            get {
                return this.baslangicSaatiField;
            }
            set {
                this.baslangicSaatiField = value;
            }
        }
        
        /// <remarks/>
        public string BitisSaati {
            get {
                return this.bitisSaatiField;
            }
            set {
                this.bitisSaatiField = value;
            }
        }
        
        /// <remarks/>
        public string SeansNotu {
            get {
                return this.seansNotuField;
            }
            set {
                this.seansNotuField = value;
            }
        }
        
        /// <remarks/>
        public int IptalEdenNo {
            get {
                return this.iptalEdenNoField;
            }
            set {
                this.iptalEdenNoField = value;
            }
        }
        
        /// <remarks/>
        public string IptalNotu {
            get {
                return this.iptalNotuField;
            }
            set {
                this.iptalNotuField = value;
            }
        }
        
        /// <remarks/>
        public string HastaBilgisi {
            get {
                return this.hastaBilgisiField;
            }
            set {
                this.hastaBilgisiField = value;
            }
        }
        
        /// <remarks/>
        public string UzmanBilgisi {
            get {
                return this.uzmanBilgisiField;
            }
            set {
                this.uzmanBilgisiField = value;
            }
        }
        
        /// <remarks/>
        public bool SeansYapildi {
            get {
                return this.seansYapildiField;
            }
            set {
                this.seansYapildiField = value;
            }
        }
        
        /// <remarks/>
        public bool HastaIptalEtti {
            get {
                return this.hastaIptalEttiField;
            }
            set {
                this.hastaIptalEttiField = value;
            }
        }

        
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void KaydetCompletedEventHandler(object sender, KaydetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KaydetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KaydetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void UzmanSeanslariniListeleCompletedEventHandler(object sender, UzmanSeanslariniListeleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UzmanSeanslariniListeleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UzmanSeanslariniListeleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Seans[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Seans[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void IptalEtCompletedEventHandler(object sender, IptalEtCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IptalEtCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IptalEtCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SonSeansBilgisiGetirCompletedEventHandler(object sender, SonSeansBilgisiGetirCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SonSeansBilgisiGetirCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SonSeansBilgisiGetirCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Seans Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Seans)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SonRandevuBilgisiGetirCompletedEventHandler(object sender, SonRandevuBilgisiGetirCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SonRandevuBilgisiGetirCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SonRandevuBilgisiGetirCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Seans Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Seans)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void RandevuKaydetCompletedEventHandler(object sender, RandevuKaydetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RandevuKaydetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RandevuKaydetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void RandevuIptalEtCompletedEventHandler(object sender, RandevuIptalEtCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RandevuIptalEtCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RandevuIptalEtCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void HastaSeanslariniListeleCompletedEventHandler(object sender, HastaSeanslariniListeleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HastaSeanslariniListeleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HastaSeanslariniListeleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Seans[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Seans[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void NotGuncelleCompletedEventHandler(object sender, NotGuncelleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NotGuncelleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NotGuncelleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591